# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version=26.1

# Mod properties
mod_version=3.1
maven_group=io.github.fifthtundrag.namereplace
archives_name=namereplace
enabled_platforms=fabric,neoforge

# Dependencies
fabric_loader_version=0.19.3
neoforge_version=26.1.0.19-beta
# carpet mod is runtime only for easier testing
carpet_version=26.1