# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft Properties
# we support all 1.21 versions but since parchment only has 1.21.1 we use that instead of plain 1.21
minecraft_version=1.21.9
# exclude @zip for parchment version
parchment_version=2025.10.05

# Mod properties
mod_version=3.1
maven_group=io.github.fifthtundrag.namereplace
archives_name=namereplace
enabled_platforms=fabric,neoforge

# Dependencies
fabric_loader_version=0.16.10
neoforge_version=21.9.16-beta
# carpet mod is runtime only for easier testing
# note for 1.21.9: carpet is not on modrinth yet and i don't like curseforge so carpet isn't here atm
#carpet_version=1.4.147